Updating these scripts to handle the change to monthly based entries
cloudbees/user-activity-monitoring-scripts pull request #4
Opened 2019-08-01 20:41 UTC by sitUboo

We have a client trying to use these in ZD 78258 and they seem to be out of sync with the plugin's current format.

2019-08-01 20:53 UTC, Evildethow requested changes
`firstDayOfWeek` is also mentioned in the README - https://github.com/cloudbees/user-activity-monitoring-scripts/blob/1133d80b60ec720dec1716b1db1595c08c653da3/README.md

2019-08-01 21:19 UTC, alecharp reviewed
Might need some explanation about when it start and when it ends.

2019-08-01 21:19 UTC, alecharp commented on README.md
> +    1 user(s) counted as Authenticated from 2018-10-01 to 2019-02-01
Shouldn't the end date be `2018-31-12` if you count by months? Or maybe I misunderstood this all month thing.

2019-08-06 13:47 UTC, sitUboo commented on README.md
> +    1 user(s) counted as Authenticated from 2018-10-01 to 2019-02-01
I updated the readme with the current output (at least against the instance I tested this against).

2019-08-06 13:48 UTC, merged